version: "3.9"

services:
  anjo-amigo-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anjo-amigo-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./backend:/app  # Permite desenvolvimento com hot reload
